"""Integration tests for the full Pass 1 project lifecycle via the HTTP API.

Uses a short synthetic video generated by ffmpeg so no real video file is needed.
"""

from __future__ import annotations

import asyncio
import subprocess
import tempfile
import time
import uuid
from pathlib import Path

import httpx
import pytest
import pytest_asyncio

# ---------------------------------------------------------------------------
# Synthetic video fixture
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def synthetic_video(tmp_path_factory) -> Path:
    """Generate a 12-second 640x360 synthetic video using ffmpeg."""
    out = tmp_path_factory.mktemp("video") / "synthetic.mp4"
    # Two 5-second segments: first with colour bars (simulates motion), then a
    # static grey scene (simulates stable play), then colour bars again.
    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi",
        "-i", "color=c=gray:s=640x360:r=30:d=12",
        "-c:v", "libx264", "-preset", "ultrafast", "-t", "12",
        str(out),
    ]
    result = subprocess.run(cmd, capture_output=True)
    assert result.returncode == 0, f"ffmpeg failed: {result.stderr.decode()}"
    return out


# ---------------------------------------------------------------------------
# App / client fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def app_with_tmp_data(tmp_path_factory):
    """Create a FastAPI test app pointed at a temporary data directory."""
    import os
    data_root = tmp_path_factory.mktemp("data")
    # Override environment so Settings picks up the temp dir.
    os.environ["PBUDDY_DATA_ROOT"] = str(data_root)
    os.environ["PBUDDY_DB_PATH"] = str(data_root / "test.db")

    # Reset the lru_cache so the new env vars are picked up.
    from pbva_api.dependencies import get_settings
    get_settings.cache_clear()

    from pbva_api.main import create_app
    return create_app(), data_root


@pytest_asyncio.fixture
async def client(app_with_tmp_data):
    app, data_root = app_with_tmp_data
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_health(client):
    resp = await client.get("/api/health")
    assert resp.status_code == 200
    assert resp.json()["ok"] is True


@pytest.mark.asyncio
async def test_create_project(client):
    resp = await client.post("/api/projects", json={"name": "Test Project"})
    assert resp.status_code == 201
    data = resp.json()
    assert data["id"]
    assert data["name"] == "Test Project"
    assert data["status"] == "created"
    # All passes (pass1-pass5) created with not_started state.
    assert len(data["passes"]) == 5
    assert all(p["state"] == "not_started" for p in data["passes"])
    assert all(p["is_dirty"] == False for p in data["passes"])


@pytest.mark.asyncio
async def test_upload_video(client, synthetic_video):
    # Create a project first.
    resp = await client.post("/api/projects", json={"name": "Upload Test"})
    project_id = resp.json()["id"]

    with open(synthetic_video, "rb") as f:
        resp = await client.post(
            f"/api/projects/{project_id}/video",
            files={"file": ("synthetic.mp4", f, "video/mp4")},
        )
    assert resp.status_code == 200
    data = resp.json()["data"]
    assert data["status"] == "video_ready"
    assert data["video_duration_s"] is not None
    assert data["video_duration_s"] > 0


@pytest.mark.asyncio
async def test_queue_pass1(client, synthetic_video):
    # Create project + upload.
    resp = await client.post("/api/projects", json={"name": "Pass1 Test"})
    project_id = resp.json()["id"]
    with open(synthetic_video, "rb") as f:
        await client.post(
            f"/api/projects/{project_id}/video",
            files={"file": ("synthetic.mp4", f, "video/mp4")},
        )

    # Queue pass 1.
    resp = await client.post(f"/api/projects/{project_id}/passes/pass1/run")
    assert resp.status_code == 200
    job = resp.json()["data"]
    assert job["status"] == "queued"
    assert job["pass_name"] == "pass1"

    # Pass state should be queued.
    resp = await client.get(f"/api/projects/{project_id}/passes/pass1")
    assert resp.json()["data"]["state"] == "queued"


@pytest.mark.asyncio
async def test_pass1_full_lifecycle(client, synthetic_video, app_with_tmp_data):
    """Run Pass 1 via the worker directly, then submit corrections and accept."""
    app, data_root = app_with_tmp_data

    # Create + upload.
    resp = await client.post("/api/projects", json={"name": "Lifecycle Test"})
    project_id = resp.json()["id"]
    with open(synthetic_video, "rb") as f:
        await client.post(
            f"/api/projects/{project_id}/video",
            files={"file": ("synthetic.mp4", f, "video/mp4")},
        )

    # Queue pass 1 via API.
    resp = await client.post(f"/api/projects/{project_id}/passes/pass1/run")
    assert resp.status_code == 200
    job_id = resp.json()["data"]["id"]

    # Run the worker synchronously (bypassing the subprocess) to avoid waiting.
    from pbva_core.config import Settings
    settings = Settings()
    from pbva_db.engine import get_engine, get_session_factory, init_db
    engine = get_engine(settings.db_path)
    session_factory = get_session_factory(engine)

    from pbva_worker.worker_loop import execute_job
    with session_factory() as session:
        from pbva_db.models import Job
        job = session.get(Job, job_id)

    execute_job(job, settings, session_factory)

    # Pass should now be waiting_for_user.
    resp = await client.get(f"/api/projects/{project_id}/passes/pass1")
    assert resp.json()["data"]["state"] == "waiting_for_user"

    # Artifacts should be registered.
    resp = await client.get(f"/api/projects/{project_id}/passes/pass1/artifacts")
    arts = resp.json()["data"]
    assert any(a["artifact_type"] == "png" for a in arts)

    # Submit corrections (empty — no changes).
    resp = await client.put(f"/api/projects/{project_id}/passes/pass1/corrections", json={})
    assert resp.status_code == 200

    # Accept pass 1.
    resp = await client.post(f"/api/projects/{project_id}/passes/pass1/accept")
    assert resp.status_code == 200

    # Project status should be in_progress.
    resp = await client.get(f"/api/projects/{project_id}")
    data = resp.json()
    assert data["status"] == "in_progress"

    # Pass state should be accepted.
    pass1 = next(p for p in data["passes"] if p["pass_name"] == "pass1")
    assert pass1["state"] == "accepted"

    # Accepted result.json must exist on disk.
    from pbva_core import paths as p_paths
    accepted_path = p_paths.pass_accepted_dir(settings.data_root, project_id, "pass1") / "result.json"
    assert accepted_path.exists(), "accepted/result.json not written"

    # Reload project (simulate browser reload).
    resp = await client.get(f"/api/projects/{project_id}")
    assert resp.json()["status"] == "in_progress"
